version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py
  builder: dirhtml
  fail_on_warning: true

python:
  install:
    - requirements: requirements-docs.txt
